config:
  graphic:
    vsync: false
    window_size_width: 1280
    window_size_height: 720
    handle_dps: false
    targeted_fps: 144
    shader_files:
      vertex_shader: "assets/shaders/shader_vertex_2d.cso"
      instanced_vertex_shader: "assets/shaders/instanced_shader_vertex_2d.cso"
      pixel_shader: "assets/shaders/shader_pixel_2d.cso"
  map:
    default_map: "town"
    map_texture: "assets/field.png"
    map_metadata: "map/assets/field.tsx"
    map:
      files:
        - "map/map_data/town.tmx"
        - "map/map_data/desert1.tmx"
        - "map/map_data/desert2.tmx"
        - "map/map_data/earthcave1.tmx"
        - "map/map_data/earthcave2.tmx"
        - "map/map_data/earthcave3.tmx"
        - "map/map_data/forest1.tmx"
        - "map/map_data/forest2.tmx"
        - "map/map_data/forest3.tmx"
        - "map/map_data/forest4.tmx"
        - "map/map_data/grassland1.tmx"
        - "map/map_data/grassland2.tmx"
        - "map/map_data/grassland3.tmx"
        - "map/map_data/iceland1.tmx"
        - "map/map_data/iceland2.tmx"
        - "map/map_data/iceland3.tmx"
      animate_files:
        - "tbd"